#!/bin/bash

# This program reset the mask step for a specified IW.

if [ -f "intarsis.config" ]; then
IW=$(grep swath_number intarsis.config | awk '{print $2}')
IW_config=true
fi

if [ -z $1 ] && [ -z $IW ]; then
	echo "Must specify IW as parameter or configure it via intarsis.config"
	echo "Example: Intarsis_09_reset_mask F1"
	exit

fi

if ! $IW_config; then
	IW=$1
fi

if [[ "$IW" == "F1" ]] || [[ "$IW" == "F2" ]] || [[ "$IW" == "F3" ]]; then
	echo "Selected $IW"
        echo "Removing mask from $IW"
	echo "$(date "+%d/%m/%y %H:%M") - Reset mask $IW" >> intarsis.log
	cd $IW
	rm corr_stack.grd std.grd mask_def.grd &> /dev/null
	cd intf_all
	for i in $(ls -d 2*/); do
		cd $i
		rm mask_def.grd &> /dev/null
		cd ..
	done
else
    	echo "You must specify the IW as F[1,2,3]"
        exit
fi


