#!/bin/bash

# FILES IN TOP FOLDER: SAFE_filelist pins.ll 
# MAKE SURE THAT YOUR $HOME/.cshrc contains the following aliases:
# alias wgetasf 'wget --http-user=username --http-password=pass'
# TODO: check if wgetasf is present and exit if it is not found

mkdir data topo
DEM=$(grep dem_filename intarsis.config | awk '{print $2}')

#check for DEM in folder
if [ ! -f $DEM ]; then
	echo "DEM is missing, please set up intarsis.config and try again"
	exit
fi

#Check for pins.ll file
if [ ! -f pins.ll ]; then
	echo "pins.ll file is missing. Create in the program's folder and try again"
	exit
fi
if [ ! -f SAFE_filelist ]; then
	echo "SAFE_filelist file is missing. Create a SAFE_filelist containing full path to all SLC folers and try again"
	exit
fi

echo "$(date "+%d/%m/%y %H:%M") - Run directory preparation" > intarsis.log


cp $DEM topo/dem.grd

cp pins.ll data/
cp SAFE_filelist data/

cd data
organize_files_tops_linux.csh SAFE_filelist pins.ll 1
organize_files_tops_linux.csh SAFE_filelist pins.ll 2

echo "$(date "+%d/%m/%y %H:%M") - Finished directory preparation" > intarsis.log

