#!/bin/bash

# This script run SBAS module.
# TODO: Allow this step for a merged product.

# Getting parameters from intarsis.config
if [ -f "intarsis.config" ]; then
IW=$(grep swath_number intarsis.config | awk '{print $2}')
ATM=$(grep atm_iter intarsis.config | awk '{print $2}')
SMOOTH=$(grep smooth_level intarsis.config | awk '{print $2}')
fi

if [[ "$IW" == "F1" ]] || [[ "$IW" == "F2" ]] || [[ "$IW" == "F3" ]]; then
	IWN=$(echo $IW | cut -c 2)
	IW_config=true
elif [[ "$1" == "F1" ]] || [[ "$1" == "F2" ]] || [[ "$1" == "F3" ]]; then
	IW=$1
	IWN=$(echo $IW | cut -c 2)
	IW_config=false
elif [ -z $1 ]; then
	echo "Must specify IW as parameters or configure it in intarsis.config"
	echo "Example: Intarsis_06_sbas F1"
	exit
else
	echo "You must specify the IW as F1,F2 or F3"
	exit
fi

# Report of the selected parameters
echo "###################################################################"
echo "Intarsis SBAS parameters:"
if $IW_config; then
	echo "Swath to process: $IW (imported from intarsis.config)"
else
	echo "Swath to process: $IW (command line)"
fi
if [ -n "$ATM" ] && [ "$ATM" -eq "$ATM" ] 2>/dev/null; then
	echo "Atmospheric iterations: $ATM (imported from intarsis.config)"
else
	ATM=0	
	echo "Disabled Atmospheric estimation (default value)"
fi
if [ -n "$SMOOTH" ] && [ "$SMOOTH" -eq "$SMOOTH" ] 2>/dev/null; then
	echo "Smoothness level: $SMOOTH (imported from intarsis.config)"
else
	SMOOTH=2	
	echo "SMOOTH level configured to 2 (default value)"
fi
echo "###################################################################"

echo "$(date "+%d/%m/%y %H:%M") - Run SBAS $IW" >> intarsis.log

rm -r SBAS &> /dev/null
mkdir SBAS &> /dev/null
cd SBAS
echo "Generating scene.tab"
awk '{$2=sprintf("%.0f",$2)}{print $2,$3}' ../$IW/baseline_table.dat > scene.tab

echo "Generating intf.tab"
rm intf.tab &> /dev/null
touch intf.tab
for z in $(ls -d ../$IW/intf_all/2*); do
i=$(basename $z)
DATE1=$(echo $i | cut -c1-7)
DATE2=$(echo $i | cut -c9-15)
DATE1_BP=$(cat ../$IW/baseline_table.dat | grep "$DATE1"\\. | awk '{print $5}')
DATE2_BP=$(cat ../$IW/baseline_table.dat | grep "$DATE2"\\. | awk '{print $5}')
B_PERP=$(echo $DATE1_BP - $DATE2_BP | bc -l)
echo "$z/unwrap.grd $z/corr.grd $DATE1 $DATE2 $B_PERP" >> intf.tab
done

echo "Getting SBAS Parameters"
#USAGE: sbas intf.tab scene.tab N S xdim ydim [-atm ni] [-smooth sf] [-wavelength wl] [-incidence inc] [-range -rng] [-rms] [-dem]
N_INTF=$(ls -1 -d ../$IW/intf_all/2* | wc -l)
N_SLC=$(cat scene.tab | wc -l)
UNWRAP_GRD=$(echo "../$IW/intf_all/$(cat ../$IW/intf_all/intflist | tail -n 1)/unwrap.grd")
XDIM=$(gmt grdinfo $UNWRAP_GRD | grep x_max | awk '{print $11}')
YDIM=$(gmt grdinfo $UNWRAP_GRD | grep y_max | awk '{print $11}')
MM=$(cat ../$IW/raw/data.in | head -n 1 | cut -c 16-23)
WAVELENGTH=$(cat ../$IW/raw/S1_"$MM"_ALL_$IW.PRM | grep radar_wavelength | awk '{print $3}')
RNG_SAMP_RATE=$(cat ../$IW/raw/S1_"$MM"_ALL_$IW.PRM | grep rng_samp_rate | awk '{print $3}' | head -n 1)
RANGE=888126 	# TODO: extract and calculate from Supermaster.prm
INC=40		# TODO: calculate incidence angle



echo "# of interferograms: " $N_INTF
echo "# of SLC: " $N_SLC
echo "Dimensions of the scene: "$XDIM" x "$YDIM
echo "Wavelength: "$WAVELENGTH
echo "Range: "$RANGE
echo "Incidence :" $INC
echo "Smooth: " $SMOOTH

echo "running SBAS code"
sbas intf.tab scene.tab $N_INTF $N_SLC $XDIM $YDIM -atm $ATM -range $RANGE -incidence $INC -wavelength $WAVELENGTH -smooth $SMOOTH -rms -dem


echo "$(date "+%d/%m/%y %H:%M") - Finished SBAS $IW" >> intarsis.log
