#!/bin/bash

# FILES IN TOP FOLDER: SAFE_filelist pins.ll 
# MAKE SURE THAT YOUR $HOME/.cshrc contains the following aliases:
# alias wgetasf 'wget --http-user=username --http-password=pass'

mkdir data orbit reframed topo merge

#check for DEM in folder
if [ -z dem.grd ]; then
	echo "DEM is missing, please rename it to dem.grd and try again"
	exit
fi
#Check for pins.ll file
if [ -z pins.ll ]; then
	echo "pins.ll file is missing. Create in the program's folder and try again"
	exit
fi
if [ -z SAFE_filelist ]; then
	echo "SAFE_filelist file is missing. Create a SAFE_filelist containing full path to all SLC folers and try again"
	exit
fi

echo "$(date "+%d/%m/%y %H:%M") - Run directory preparation" > Intarsis_stage


cp dem.grd topo/dem.grd

cp pins.ll data/
cp SAFE_filelist data

cd data
organize_files_tops_linux.csh SAFE_filelist pins.ll 1
organize_files_tops_linux.csh SAFE_filelist pins.ll 2


