#!/bin/bash

# This script run SBAS module for an specific IW.

if [ -z $1 ]; then
	echo "Must specify IW and coherence threshold as parameter"
	echo "Example: Intarsis_04_mask F2"
	exit
elif [[ "$1" == "F1" ]] || [[ "$1" == "F2" ]] || [[ "$1" == "F3" ]]; then
	IW=$1
	echo "Selected $IW"
else
	echo "You must specify the IW as F1,F2 or F3"
	exit
fi

echo "$(date "+%d/%m/%y %H:%M") - Run SBAS $IW" >> Intarsis_stage

rm -r SBAS &> /dev/null
mkdir SBAS &> /dev/null
cd SBAS
echo "Generating scene.tab"
awk '{$2=sprintf("%.0f",$2)}{print $2,$3}' ../$IW/baseline_table.dat > scene.tab

echo "Generating intf.tab"
rm intf.tab &> /dev/null
touch intf.tab
for z in $(ls -d ../$IW/intf_all/2*); do
i=$(basename $z)
DATE1=$(echo $i | cut -c1-7)
DATE2=$(echo $i | cut -c9-15)
DATE1_BP=$(cat ../$IW/baseline_table.dat | grep "$DATE1"\\. | awk '{print $5}')
DATE2_BP=$(cat ../$IW/baseline_table.dat | grep "$DATE2"\\. | awk '{print $5}')
B_PERP=$(echo $DATE1_BP - $DATE2_BP | bc -l)
echo "$z/unwrap.grd $z/corr.grd $DATE1 $DATE2 $B_PERP" >> intf.tab
done

echo "Getting SBAS Parameters"
#USAGE: sbas intf.tab scene.tab N S xdim ydim [-atm ni] [-smooth sf] [-wavelength wl] [-incidence inc] [-range -rng] [-rms] [-dem]
N_INTF=$(ls -1 -d ../$IW/intf_all/2* | wc -l)
N_SLC=$(cat scene.tab | wc -l)
UNWRAP_GRD=$(echo "../$IW/intf_all/$(cat ../$IW/intf_all/intflist | tail -n 1)/unwrap.grd")
XDIM=$(gmt grdinfo $UNWRAP_GRD | grep x_max | awk '{print $11}')
YDIM=$(gmt grdinfo $UNWRAP_GRD | grep y_max | awk '{print $11}')
MM=$(cat ../$IW/raw/data.in | head -n 1 | cut -c 16-23)
WAVELENGTH=$(cat ../$IW/raw/S1_"$MM"_ALL_$IW.PRM | grep radar_wavelength | awk '{print $3}')
RNG_SAMP_RATE=$(cat ../$IW/raw/S1_"$MM"_ALL_$IW.PRM | grep rng_samp_rate | awk '{print $3}' | head -n 1)
RANGE=888126 # TODO: extract from Supermaster.prm
INC=40
SMOOTH=2
ATM=3



echo "# of interferograms: " $N_INTF
echo "# of SLC: " $N_SLC
echo "Dimensions of the scene: "$XDIM" x "$YDIM
echo "Wavelength: "$WAVELENGTH
echo "Range: "$RANGE
echo "Incidence :" $INC
echo "Smooth: " $SMOOTH

echo "running SBAS code"
sbas intf.tab scene.tab $N_INTF $N_SLC $XDIM $YDIM -atm $ATM -range $RANGE -incidence $INC -wavelength $WAVELENGTH -smooth $SMOOTH -rms -dem
